language: node_js
sudo: false

node_js:
  - "6"
  - "6.1"
  - "5.11"

before_script:
  - npm install

script: npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: surge
  project: ./build
  domain: recipebox.surge.sh
